### ISSUE TITLE
Layout_width="match_parent" dont work in constraint layout

### ISSUE THREAD

**Issue by jrcacd** [HITGIF/TextFieldBoxes#12]

**Comment by HITGIF** [comment]
**fixed in release 1.2.1**

**Comment by jrcacd** [comment]
The bug is still alive!
![image](https://user-images.githubusercontent.com/26005662/30274680-61e612ca-96f6-11e7-8124-710b2d689708.png)

**Comment by HITGIF** [comment]
what is its height setting? Or could you give me the xml for it, with its parent

**Comment by jrcacd** [comment]
<ObservableScrollView
        android:id = "@+id/scrollView"
        android:layout_width = "match_parent"
        android:layout_height = "match_parent"
        android:fillViewport = "true"
        android:layout_marginTop="?attr/actionBarSize"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/menu"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginLeft="8dp"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintVertical_bias="1.0"
        android:layout_marginRight="8dp">

		<android.support.constraint.ConstraintLayout
		xmlns:inner_app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:focusable="true"
		android:fitsSystemWindows="true"
        android:focusableInTouchMode="true"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:maxWidth="@dimen/tamanho_maximo_horizontal"
        android:paddingTop="10dp"
        android:descendantFocusability="beforeDescendants"
        android:layout_gravity="center_horizontal"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent">
		
		 <studio.carbonylgroup.textfieldboxes.TextFieldBoxes
                android:id="@+id/portugues"
                android:layout_height="wrap_content"
                android:layout_width="match_parent"
                inner_app:layout_constraintStart_toStartOf="parent"
                inner_app:layout_constraintTop_toTopOf="parent"
                inner_app:layout_constraintEnd_toEndOf="parent"
                inner_app:maxLines="10"
                inner_app:iconSignifier="@drawable/ic_import_contacts_black_24dp"
                inner_app:hint="@string/portugues"
                inner_app:labelText="@string/portugues"
                android:layout_marginTop="60dp"/>

**Comment by HITGIF** [comment]
Well, things worked fine in mine...
![image](https://user-images.githubusercontent.com/16971971/30509034-29aa7892-9a6b-11e7-867c-5ac0a9b5fbc5.png)
```xml
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/scrollView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:fillViewport="true"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintHorizontal_bias="1.0"
    app:layout_constraintLeft_toLeftOf="parent"
    app:layout_constraintRight_toRightOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@+id/menu"
    app:layout_constraintVertical_bias="1.0">

    <android.support.constraint.ConstraintLayout xmlns:inner_app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginEnd="5dp"
        android:layout_marginStart="5dp"
        android:descendantFocusability="beforeDescendants"
        android:fitsSystemWindows="true"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:gravity="center"
        android:maxWidth="300dp"
        android:paddingTop="10dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <studio.carbonylgroup.textfieldboxes.TextFieldBoxes
            android:id="@+id/portugues"
            android:layout_width="284dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="60dp"
            inner_app:iconSignifier="@drawable/ic_location_on_black_24dp"
            inner_app:labelText="portugues"
            inner_app:layout_constraintEnd_toEndOf="parent"
            inner_app:layout_constraintStart_toStartOf="parent"
            inner_app:layout_constraintTop_toTopOf="parent"
            tools:layout_editor_absoluteX="8dp">

            <studio.carbonylgroup.textfieldboxes.ExtendedEditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:hint="portugues" />

        </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>
    </android.support.constraint.ConstraintLayout>
</ScrollView>
```
See if the 1.3.0 release solves it :)

**Comment by HITGIF** [comment]
Well, things worked fine in mine...

![image](https://user-images.githubusercontent.com/16971971/30509051-ea549852-9a6b-11e7-8799-de1df1ab0fc6.png)


```xml
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/scrollView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:fillViewport="true"
    app:layout_constraintBottom_toBottomOf="parent"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintHorizontal_bias="1.0"
    app:layout_constraintLeft_toLeftOf="parent"
    app:layout_constraintRight_toRightOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toBottomOf="@+id/menu"
    app:layout_constraintVertical_bias="1.0">

    <android.support.constraint.ConstraintLayout xmlns:inner_app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginEnd="5dp"
        android:layout_marginStart="5dp"
        android:descendantFocusability="beforeDescendants"
        android:fitsSystemWindows="true"
        android:focusable="true"
        android:focusableInTouchMode="true"
        android:gravity="center"
        android:maxWidth="300dp"
        android:paddingTop="10dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <studio.carbonylgroup.textfieldboxes.TextFieldBoxes
            android:id="@+id/portugues"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="70dp"
            inner_app:iconSignifier="@drawable/ic_location_on_black_24dp"
            inner_app:labelText="portugues"
            inner_app:layout_constraintEnd_toEndOf="parent"
            inner_app:layout_constraintStart_toStartOf="parent"
            inner_app:layout_constraintTop_toTopOf="parent"
            android:layout_marginLeft="8dp"
            inner_app:layout_constraintLeft_toLeftOf="parent"
            android:layout_marginRight="8dp"
            inner_app:layout_constraintRight_toRightOf="parent">

            <studio.carbonylgroup.textfieldboxes.ExtendedEditText
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:hint="portugues" />

        </studio.carbonylgroup.textfieldboxes.TextFieldBoxes>
    </android.support.constraint.ConstraintLayout>
</ScrollView>
```
See if the release 1.3.0 solves it :)
