### ISSUE TITLE
Wrap_content height issue

### ISSUE THREAD

**Issue by Domovoy19** [HITGIF/TextFieldBoxes#9]
Hello, thanks for your lib, looks really nice :)

But i found some problem
`android:layout_height="wrap_content"` make view's height matching to parent height.
Expected behavior: height corresponds to the height of the EditText's lines

**Comment by HITGIF** [comment]
Fixed in 4fe8aef45f9cbdd42e9f809b4deb093709448b8a, will come out in the next release :)

**Comment by HITGIF** [comment]
It's now bug-free in release 1.2.0 🎉🎉🎉
Check out README for more detail :)

**Comment by Domovoy19** [comment]
Hello, thanks for update :)
I tested it and my problem is still here `wrap_content` height takes whole parent layout:<
Also i got another one, `match_parent` width are takes only for a label text width.

![image](https://user-images.githubusercontent.com/26565071/30255518-96dfc8cc-96ce-11e7-8531-1889466878af.png)

**Comment by HITGIF** [comment]
What's outside the tfb? A constraint layout?

**Comment by HITGIF** [comment]
See whether the 1.2.1 release solves your problem

**Comment by Domovoy19** [comment]
Yes, it's constraint layout and seems that in 1.3.1 issue still alive :<

**Comment by abc612008** [comment]
I cannot reproduce the bug. Could you provide a minimal, complete, and verifiable example (MCVE) please?

**Comment by Domovoy19** [comment]
Oh, i got it. This issue reproduce in `com.android.support.constraint:constraint-layout:1.1.0-beta1` version

**Comment by HITGIF** [comment]
Could give me the whole xml code?

**Comment by Domovoy19** [comment]
Here: 
[activity_text_boxes.xml](https://gist.github.com/Domovoy19/d5959e28817544546a41c212e005fb99)
with `compile 'com.android.support.constraint:constraint-layout:1.1.0-beta1'`

**Comment by HITGIF** [comment]
OK I got it... the bug occurs when width is set to 0dp
Now fixing it :)

**Comment by HITGIF** [comment]
fixed in release 1.3.2 :)
